api_platform:
    version: '0.1.0'

    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    resource_class_directories:
        - '%kernel.project_dir%/src/IdentityAccess/Infrastructure/Access/Query'
        - '%kernel.project_dir%/src/IdentityAccess/Infrastructure/Identity/Query'

    mapping:
        paths:
            - '%kernel.project_dir%/src/IdentityAccess/Infrastructure/config/api_platform/resources'

    collection:
        order_parameter_name: _order
        pagination:
            enabled_parameter_name: _pagination
            page_parameter_name: _page
            items_per_page_parameter_name: _page_size
            client_items_per_page: true
            items_per_page: 10
            maximum_items_per_page: 500
        exists_parameter_name: _exists

    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        ApiPlatform\Core\Exception\InvalidArgumentException: 400
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

        # Custom mapping
        Symfony\Component\Security\Core\Exception\AuthenticationException: 401
        IdentityAccess\Infrastructure\Access\Security\BadCredentialsException: 401
        IdentityAccess\Infrastructure\Access\Security\AccountDisabledException: 401
        IdentityAccess\Ui\Access\AccessDeniedException: 403

    show_webby: false
