api_platform:
    version: '0.1.0'
    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    resource_class_directories:
        - '%kernel.project_dir%/src/IdentityAccess/Infrastructure/Access/Query'
        - '%kernel.project_dir%/src/IdentityAccess/Infrastructure/Identity/Query'

    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        ApiPlatform\Core\Exception\InvalidArgumentException: 400
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

        # Custom mapping
        IdentityAccess\Infrastructure\Access\Security\AuthenticationException: 401
        IdentityAccess\Infrastructure\Access\Security\BadCredentialsException: 401
        IdentityAccess\Infrastructure\Access\Security\AccountDisabledException: 401
        IdentityAccess\Ui\Access\AccessDeniedException: 403

    show_webby: false
