doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'

        # exclude system tables
#        schema_filter: ~^(?!%event_store.dbal.table_name%|%messenger.doctrine.table_name%|%saga.state.doctrine.dbal.table_name%)~
        schema_filter: ~^(?!%event_store.dbal.table_name%|%messenger.doctrine.table_name%)~

        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            datetime_immutable: Common\Shared\Infrastructure\Doctrine\DateTimeType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            IdentityAccess:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/IdentityAccess/Infrastructure/config/doctrine'
                prefix: IdentityAccess\Infrastructure
                alias: IdentityAccess
